spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: zyc1666033672
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            filters: stat,wall

            stat-view-servlet:
                login-username: admin
                login-password: admin
            web-stat-filter:
                enabled: true
        url: jdbc:mysql://localhost:3306/WordListDB?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    redis:
        port: 6400
        database: 1

mybatis:
#    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath*:mapper/*.xml
    type-aliases-package: com.zyc.wordlistsp.pojo

list-page:
    limitation: 3
server:
    port: 8084
