spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        username: root
        password: zyc1666033672
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            filters: stat,wall

            stat-view-servlet:
                login-username: admin
                login-password: admin
            web-stat-filter:
                enabled: true
        url: jdbc:mysql://localhost:3306/WordListDB?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true

mybatis:
    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath*:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: com.zyc.wordlistsp.pojo

mybatis-plus:
    configuration:
        map-underscore-to-camel-case: false
